import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}flex h-screen w-screen bg-gradient-to-b from-[#285d98] via-[#5fa1e3] to-[#e1d4c6]`}
      >
        {children}
      </body>
    </html>
  );
}
